import { MPMC_WQ_HEADER_BYTES } from "./MpmcWorkQueue.js";

export interface EmitWasmMpmcOptions {
  /** Exported claim function name. Default `"claim_ticket"`. */
  readonly functionName?: string;
  /** Shared-memory page bounds emitted on the import. Default `{ min: 1, max: 65536 }`. */
  readonly memoryPages?: { readonly min: number; readonly max: number };
  /** Byte offsets of the two ticket lanes. Defaults match MpmcWorkQueue's compact header. */
  readonly headerOffsets?: WasmMpmcClaimOffsets;
}

export interface WasmMpmcClaimOffsets {
  readonly enqueueTicket: number;
  readonly dequeueTicket: number;
}

const ENQUEUE_TICKET_BYTE_OFFSET = 0;
const DEQUEUE_TICKET_BYTE_OFFSET = 4;
const IDENT = /^[A-Za-z_$][0-9A-Za-z_$]*$/;

function watName(name: string): string {
  if (!IDENT.test(name)) {
    throw new Error(`emitWasmMpmc: invalid functionName '${name}'`);
  }
  return name;
}

function checkPages(pages: { readonly min: number; readonly max: number }): void {
  if (
    !Number.isInteger(pages.min) ||
    !Number.isInteger(pages.max) ||
    pages.min < 1 ||
    pages.max < pages.min
  ) {
    throw new Error(`emitWasmMpmc: invalid shared-memory page bounds ${pages.min}..${pages.max}`);
  }
}

function checkOffset(name: string, offset: number): void {
  if (!Number.isSafeInteger(offset) || offset < 0 || (offset & 3) !== 0) {
    throw new Error(`emitWasmMpmc: ${name} byte offset must be a non-negative 4-byte multiple, got ${offset}`);
  }
}

/** Emit a tiny WAT module for the MpmcWorkQueue dequeue claim primitive.
 *
 * The export mirrors:
 *
 *   R = Atomics.load(header, DEQUEUE_TICKET_LANE)
 *   W = Atomics.load(header, ENQUEUE_TICKET_LANE)
 *   if ((W - R) | 0 <= 0) return -1
 *   return Atomics.add(header, DEQUEUE_TICKET_LANE, 1)
 *
 * It intentionally claims ONLY the ticket. The rest of `pull()` remains in the
 * TypeScript queue so held-claim riding, per-slot generation checks, teardown
 * strand release, payload decode, and flow-scale side effects stay identical to
 * the proven JS implementation.
 */
export function emitWasmMpmc(opts: EmitWasmMpmcOptions = {}): string {
  const functionName = watName(opts.functionName ?? "claim_ticket");
  const memoryPages = opts.memoryPages ?? { min: 1, max: 65_536 };
  checkPages(memoryPages);
  const offsets = opts.headerOffsets ?? {
    enqueueTicket: ENQUEUE_TICKET_BYTE_OFFSET,
    dequeueTicket: DEQUEUE_TICKET_BYTE_OFFSET,
  };
  checkOffset("enqueueTicket", offsets.enqueueTicket);
  checkOffset("dequeueTicket", offsets.dequeueTicket);

  return `;; generated by emitWasmMpmc; headerBytes=${MPMC_WQ_HEADER_BYTES}
(module
  (import "env" "memory" (memory ${memoryPages.min} ${memoryPages.max} shared))
  (func (export "${functionName}") (result i32)
    (local $r i32)
    (local $w i32)
    (local.set $r
      (i32.atomic.load align=4 (i32.const ${offsets.dequeueTicket})))
    (local.set $w
      (i32.atomic.load align=4 (i32.const ${offsets.enqueueTicket})))
    (if (i32.le_s
          (i32.sub (local.get $w) (local.get $r))
          (i32.const 0))
      (then
        (return (i32.const -1))))
    (i32.atomic.rmw.add align=4
      (i32.const ${offsets.dequeueTicket})
      (i32.const 1))))`;
}

function u32leb(n: number): number[] {
  if (!Number.isSafeInteger(n) || n < 0) {
    throw new Error(`emitWasmMpmcBytes: invalid unsigned integer ${n}`);
  }
  const out: number[] = [];
  do {
    let b = n & 0x7f;
    n = Math.floor(n / 128);
    if (n !== 0) b |= 0x80;
    out.push(b);
  } while (n !== 0);
  return out;
}

function s32leb(n: number): number[] {
  if (!Number.isSafeInteger(n) || n < -0x80000000 || n > 0x7fffffff) {
    throw new Error(`emitWasmMpmcBytes: invalid signed i32 ${n}`);
  }
  const out: number[] = [];
  let value = n | 0;
  for (;;) {
    const b = value & 0x7f;
    value >>= 7;
    const done =
      (value === 0 && (b & 0x40) === 0) ||
      (value === -1 && (b & 0x40) !== 0);
    out.push(done ? b : b | 0x80);
    if (done) return out;
  }
}

function bytesOf(s: string): number[] {
  return Array.from(s, (c) => c.charCodeAt(0));
}

function section(id: number, data: number[]): number[] {
  return [id, ...u32leb(data.length), ...data];
}

/** Emit the same `claim_ticket` module as a binary wasm buffer. This is the
 * runtime counterpart to the WAT emitter above: topology code cannot depend on a
 * WAT compiler, but it can synchronously construct a `WebAssembly.Module` from
 * these bytes on the allocating thread and send that clone-safe Module to peers. */
export function emitWasmMpmcBytes(opts: EmitWasmMpmcOptions = {}): Uint8Array<ArrayBuffer> {
  const functionName = watName(opts.functionName ?? "claim_ticket");
  const memoryPages = opts.memoryPages ?? { min: 1, max: 65_536 };
  checkPages(memoryPages);
  const offsets = opts.headerOffsets ?? {
    enqueueTicket: ENQUEUE_TICKET_BYTE_OFFSET,
    dequeueTicket: DEQUEUE_TICKET_BYTE_OFFSET,
  };
  checkOffset("enqueueTicket", offsets.enqueueTicket);
  checkOffset("dequeueTicket", offsets.dequeueTicket);

  const typeSection = section(1, [
    0x01, // one type
    0x60, 0x00, 0x01, 0x7f, // func () -> i32
  ]);
  const importSection = section(2, [
    0x01,
    0x03, ...bytesOf("env"),
    0x06, ...bytesOf("memory"),
    0x02, // import kind: memory
    0x03, // shared limits with max
    ...u32leb(memoryPages.min),
    ...u32leb(memoryPages.max),
  ]);
  const functionSection = section(3, [0x01, 0x00]);
  const exportSection = section(7, [
    0x01,
    ...u32leb(functionName.length), ...bytesOf(functionName),
    0x00, 0x00, // func 0
  ]);

  const body: number[] = [
    0x01, 0x02, 0x7f, // one local decl: 2 x i32
    0x41, ...s32leb(offsets.dequeueTicket),
    0xfe, 0x10, 0x02, 0x00, // i32.atomic.load align=4 offset=0
    0x21, 0x00, // local.set 0
    0x41, ...s32leb(offsets.enqueueTicket),
    0xfe, 0x10, 0x02, 0x00,
    0x21, 0x01,
    0x20, 0x01, // local.get w
    0x20, 0x00, // local.get r
    0x6b, // i32.sub
    0x41, 0x00,
    0x4c, // i32.le_s
    0x04, 0x40, // if void
    0x41, 0x7f, // i32.const -1
    0x0f, // return
    0x0b, // end if
    0x41, ...s32leb(offsets.dequeueTicket),
    0x41, 0x01,
    0xfe, 0x1e, 0x02, 0x00, // i32.atomic.rmw.add align=4 offset=0
    0x0b, // end func
  ];
  const codeSection = section(10, [
    0x01,
    ...u32leb(body.length),
    ...body,
  ]);

  return new Uint8Array([
    0x00, 0x61, 0x73, 0x6d,
    0x01, 0x00, 0x00, 0x00,
    ...typeSection,
    ...importSection,
    ...functionSection,
    ...exportSection,
    ...codeSection,
  ]);
}
